travis:
  secure:
    BINSTAR_TOKEN: lkfu852uZn8+9ZV3EfQBKtSEo0az1dBfaLFDsrPe5tKP+jy8Xj+6oIkA6IsMP9/3vNOfB8AmuUrkbJzdvF4STEHguJLaeVyDFPHXgUkWJNnL0BKjR4yM0DDts508IUWF28v69PMkmqCRqL74os1hXoBO8wP5YN63+jVTRsyxAsSCpzY+Epi1Ui1pbi5dyOu3/YP5hejsXB0ajpGlIoK4+1EE3/m0u38GaiMC3lMRu3C5zCj1DDe2mCDK9pilNYZKbWk9JWk6f+/OyMfqa3Nq1XC1v1qTT1Ofrbds6PYk1iElUZIVE65PT28B9RQM7hGD1sZZQBxPc4OIBycyDKxHM7SBwKqO30HVrCUrYkn1Qwg2sYN8qkT+qCpT2WtKBF8KG35GWbjBbbUtHRkPY+rRzOXYVkOQOIWRpFi9kD5cPDeoswz/28pFRMRH+rSEhTKhB6UikZMdc2E0mshv5c5n16Ddg/1nibMJq7ngM5x0DH76N1z7Mx6bejveb0uJyN46O3MB51Trxac0KXG/IvVHVoilG3iDXNDPENsVadYaqzj44jZaz7FgIQ5vHpDX/bwtlxNucVZCWM6qKdgAeSr+/eppBxjcICIc0OlTEunA4M2eDPKzSuDrUWVNFSB1KDMWiTMoCW1cw2j+XpLmDTTldJjjZZwxVwvUigRmCIktQoA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
