travis:
  secure:
    BINSTAR_TOKEN: spm0mka/EzjHzgouu5m6PochROK9DbLmHu4My2Jf2xsTXZDwR9KmtWmQ7DqQMSMQ9bI63sCaKLTA0Q27JIPTnWoz2RAOgH+1EcmTyaVasehruhJFUcL+aON9On51a3hArPjG4bhaSP4qujDPLGyWceORFWsHJLqGElytEyWkkFsrHBZo7TRMzSs+qxFi0NqJLx9SqqHCtGc1+fx+Z4/NDB9JludRNCv2V39XDxyZzlV2tTTJMKpwfJLHZvanTbdmmvJ75Z5xuVziDz9qOlmXCaf5v8utIK06E9aNXadsBPPnVdlCUXJKVBXQTW78T9jhZf2MbLcLJi2UI+A2NFW/nQEdaA5UNm2LkTijYBfK7wdSipzsLHn/BJoD3YSCyuaybkIOGzzKvXpZIlfIs/UqWnMfCc5JyXWbOUC51Z1krhRpsomhIBJ352o7A4LhZFVZ4B6bbBqqlpKw+20dfQPMJiu2L7QUSLbZsJNJzzgybd3EGyogakhtSuKB+BcVmeAEON8bC5VtnkM8jO6b8JGYRScjO6AvqP8lzgr5iW1JBLnoVxPJKMS2BIYVq5YDFdiYvDHeZLCJ1gdDsyd85q8TaxZ9nWp4S5BcfwOjMDY4c1zGvTtpxapxAQLRBkf+nALxbRP8b4VQhEjb7TfssmzuKqYRgtSJ8RNdj9sN9oxEwxA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
