travis:
  secure:
    BINSTAR_TOKEN: Gx0BE/+uo0xGOW5EOOsqA7Jgupf9027u3sJYx//Dr8wwPb/haKt60Ruw5wtFO6nj56M1zsjHodhrnHZpZQTVBoqvPOn+PC2syS9cDQpG25dwfFjanDqdupAHzWj1RHcantXMPpqKzrDA9cQEc+ymuHw9kzkQGa41j7DRaMPYf1c58zsvUUR1BFJZVHsX2vyzeg1P56mtUA9MA9BEA/ge4LyZy7+eSLzK6+8PXN73O4eLx2fZ4vo2qL/yLF0BGmfLx+XVznzXgojGRGmU6xdznb5x8RU+7FWDOj4U1wscxUlzBLUS6orycKJdwx3nIlLKI3q2Fv24yuchsudpc0n6ZY/zK6YLsIf2jBIY/aL9KVvHUYlIosTWH1LDhT7AVgiKkwS4JDp6QwNmaHNKbNI1f1vpXdNt8M5hUvXX/+E5lEiROfv6GnNSIunjKtI5zog0B80ANYvfnl3btRTjQmG6L8cqljNt6JNbfzen7v4iiDwawl5csUNZYS3AhgW7CpVIKeeKaJysGUf0dklRt6XAj84OSr5Xz6fd3AjzfRzoowJzgLlQTNp+O1ZdiryyQqThEriDvxrQ6R4W7MJgV+29eD7vfbyUPhoFFctWvMpGQIbEdOMCcU+H2R4lSPf6IXSJaAW5Hco1/H+fjUvFtm0rdwT7FvOZbc74xiHjYkrGuLc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
