travis:
  secure:
    BINSTAR_TOKEN: rouq2tJ/2jIkiZVdBLSupw38+s0fk5D1ZZiL8lrIk8IRYRnr45FPfAgVtmXKrZUnJoQSzhz1TKiAVikobJv9bIeSVKeFyBQxSUYvZgVjXAGh2PEhe/geVZQngV0fagmbkkVcx7WCGBuFl1TgrmwfqolCmoS5BhbnVCI99vHZsMvOOQ0AMOpr8TBoRwqFQXfMDfRfPw+bQit4Mjrr7kNj1q+RoG56Zm+HiJtIqTP2pQONQHJ4vvV+Ri1+HiqUkvkDbPXNgZneon0mv0GImK1IR4sdRCL94at05SXOdyokfdHqMwkqPATnjXX46oFBplazxpyn/naXIY1A2J9AmbKsOqflR3N1VbEaU+4R3H6i6nBRLZ3vQKzIdnqUqS2yozDaYTThO/+9sZWhMBxTtE+fRzDgd0hoYRkW2c88181cZlnOwQqVGedtgs3Uk5UPNFpkkl6x1HMBumaHQEd72nrqrI99bUwB2iOJVPcib46cnt8hoR3x67Uav1kYgYXBfsA0TvcMd7K5nEeBKxViHnVYCUUdLwJ1DfzagDhPrddupmgdzcQ/R994q8Jq7AUz7QktfwX6G3aWXYn/SHdQ8WvyPikZapwykxOvoD3t1yo5ABc65DLNVd2XV1zWwx/RIKjhb1/xINLl0O7Sfcr0bvwm+T0RpNrU4MJN3zuib6MolTA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
