travis:
  secure:
    BINSTAR_TOKEN: UjA3nZwP+pZi2FQFIZcHA6vdpGUlFIO+rDNechqUtp81xc6niLf15eEX/AQ0htP00+X3eWDTmhnzmf1KrJvGIsAdXvuDYSixxbW2S6jRmwfqlLm5acikGcTOXn+edtRNZiP7riS3CNrOjzFqqunTOMYYnS4FjR17XttXasWG6UWksNXQSMDDTw9pgMP4rptvffdpZehFxzbniLwpUbD0sqhqquIx35WH6Y166tWrRxNNL+ao21h3ucwSryUSEvyjxJ7v++abf/k97r44u5DIr71krSIeEBjVDJYa5etKjLn1bMnKqaWgmSvNY2xIMs5fwHrmAVssc7KXuvJQrT3szRny3NqiSItwbDHGWvQbNMqHFQzKxnWM6XNydIehRH9+vNOBWw6Ag/h2JXs2tI0NovrFSDGwyfojUeCm76qcFDGZJqN1zcN96LYdLagVeIT3mp+K6hkkfyJPntu+/jaTN9HZksqPxcpQuLgyzAKg1BfYSt/UoPu8+bf4AZBVmAkt+Yj3zzZe0NAjJUc8F3FVCwPM4DLg83+fjzt7Ie0WFjVsEa0dYmnWwX/BrltVkIaaPjWClAukGoNpNLDT57USxnrsCo3SGYsT1D0ZAWiVrgYDZXb2kzbOY5xObWILFFtVPR+vBMtOU7LQllzuaJwvBMlRH+EYs78mGzF4aYyY8Ao=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
