travis:
  secure:
    BINSTAR_TOKEN: Q5QqXg1vKtV5S2eE5/ZY1RSaidr+FENIU7LnhEKncJzx6TPZkUbw7yEwjQ/CYrPaxGM9JhGhRtr+ny6MaPzcaG/M3EzeayDhq4o2k+i18GgvchXd2+rEuyQVny8tZybmUbui77XNl1VMPSg2N8qraRP4oMb2nJySCB9Bepxeo0ZlBLc1OyW0m91SfFo3q6/Mni04vrahm0nRFGHa/9nDV1VGEoTKKFGTKlWCeFld1apMcbB0U61jfvPg61yLt9FPmKz35ae6pTj2Dn0EUTnGlsAutiX1OcjNr17diG6l33vHh45t0HFjsj9sm/Jcbn5m3AcdgReHUT5GeNsFI1NHufSGnFOeXlC+nHc0+Tl8XbDbgKK+/MfCOCtm441W8/EFXWe9JkE7THnNwTBT4wVHlX/iLYqFRUY/yi8ppWby1Euwangh7Vk8uI191CdS8RT9H07nVGAxW3HiA/Dv7LsJmyfHyhZmbJkM69byOmmpQjoQUTsxPovT0HEgAmR9F045Wz3GxPncMNMPqsVYW7EDh3QqLhPoTd6sjGx2s3mfiXCr626NYJhM8E3DAKG+acuzPLK+G5JtK4dxYw0OBx6/MFW8999ITTZj87/C2xb5rw7sxI7/JxKzNXP4nvD+lDfKiAWa8BqTSV6/PthQearVnzrOOfZqRjDQ7/hnDORAqXA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
