travis:
  secure:
    BINSTAR_TOKEN: KbDvC7VnZo/MSjOC5YbxRQ9YPPQPuk36+a9RjwLe2jyovpmWlJh9A5dH6u45wRvv74vIaXFqln/OSgC7EOtXfl07qeqk2dlVrfQq8S2wSdCRdUeOGEJEpRTezdkNKQh+hi0BgPuLF+N5KavJpRALkGS7J6vvEoEIlhRRqwNh9O7tA03zcC1OZdKwn+fkznIBWc6VmWX6eIIfYl1pCOOuZwTtTF+RqAsoV01OYFIk7MW9SloWsae1LSCfR7JusMg6x489G8Fx4Rw3ujDhiizMzncktcuwJ058QTOQGwVLRqoAFE0EgFp0hdrRFDPAfWzBsVAGb3ay6+XKt9s9WbLgZZygAt58zhzQUm71Twm7pZc8Dgu5t0XTMM7fpi8buPga5sM+Mwd/+Q+89qSPhTwOCpZ3t/HzwaKktdqJcn84eLhENWJmeET/UyYybr4dffBm8Ax1XCvSsIILdkapjRb5ihW4hKp3++mdbLH0AyMzuvwWjA+wafQlTpCSfAEvUNtx0n50H2rRglOaDLrruASJkMHAqjSuiooFJ6m/fgjH0CsEnIqiEPSkWhWdEbYkJ0JtLg9tcCVAPr+weyTa8gnJhDAh/Yi2nmBTYMBO8c8AP79h4Ng69sseZDMGXYKrG1bNtzxZYuMQkBEBqSIu1f0QV/J47Hy+18iPyBf9wIPRc8w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
