travis:
  secure:
    BINSTAR_TOKEN: iptzYjXCu9DCUQDFy/b9FF9gxdtoFa2g+q47ainB6ewAD7PgvzlZ9lIP7xJ/+Eo+k7ltCjLhL/YSYZDNfcOJONJSc788bURJdfJZdas+iywAntkKjKLenUx/tUFP8zoZssKu9BAtZu6jsEyTyWu95wL73DP9b4NlQS4/62EG+ACGcJp+1vxepjczuyMV5Pv2oe15yI6IqNm4Ts2ovppRs0M1vdUk7bb+Y7kpXADni2O09jgilp4J0vYJuYiofCp9anPo3aUj7vK6hSLFNPikKDMJ/aKXmpdcrUYcHQccnOOxbJsBcRFgJbf2MwQG8ar0HztADPkyySNXoaujtCMVx4hrsSDivai5NPU7jo/MTeDbooT/5H3cmP6bGWGs4xCedst9O80ml8AMbRM/PGY2Is37BqhB9PSY4GF7dI8V643AM4crMIIVogFY9b/YafdyCQ/TwPDDpntUCFszVC13wzRX+y9O4yafldOG4yGKA2TH1WJV5e9X+eg6+QAV0WRXX2Z/bb6XjF2cYgwkdopyOepwBn8P7uQba8e0NWDyIFfyR2cqVrHPC1FuDQtuDdECTSY98MZ2mG0KB3nloTMBbALYmJNwAQjIHKLacp2p428DpQCJRGp1lapDGKv66xSUTpnYlvx5xYKzQYo8fSEi6Q0ZKr0X7mvdhf39pzeuwh0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
